package BEAN;
// Generated 19/10/2023 14:15:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AutoresVc generated by hbm2java
 */
@Entity
@Table(name="autores_vc"
    ,catalog="db_vivian_carvalho"
)
public class AutoresVc  implements java.io.Serializable {


     private int idautoresVc;
     private String nomeVc;
     private Date dataNascimentoVc;
     private String nacionalidadeVc;
     private String emailVc;
     private String biografiaVc;
     private String generoLiterario;
     private String destaquesVc;

    public AutoresVc() {
    }

    public AutoresVc(int idautoresVc, String nomeVc, Date dataNascimentoVc, String nacionalidadeVc, String emailVc, String biografiaVc, String generoLiterario, String destaquesVc) {
       this.idautoresVc = idautoresVc;
       this.nomeVc = nomeVc;
       this.dataNascimentoVc = dataNascimentoVc;
       this.nacionalidadeVc = nacionalidadeVc;
       this.emailVc = emailVc;
       this.biografiaVc = biografiaVc;
       this.generoLiterario = generoLiterario;
       this.destaquesVc = destaquesVc;
    }
   
     @Id 

    
    @Column(name="idautores_vc", unique=true, nullable=false)
    public int getIdautoresVc() {
        return this.idautoresVc;
    }
    
    public void setIdautoresVc(int idautoresVc) {
        this.idautoresVc = idautoresVc;
    }

    
    @Column(name="nome_vc", nullable=false, length=45)
    public String getNomeVc() {
        return this.nomeVc;
    }
    
    public void setNomeVc(String nomeVc) {
        this.nomeVc = nomeVc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento_vc", nullable=false, length=10)
    public Date getDataNascimentoVc() {
        return this.dataNascimentoVc;
    }
    
    public void setDataNascimentoVc(Date dataNascimentoVc) {
        this.dataNascimentoVc = dataNascimentoVc;
    }

    
    @Column(name="nacionalidade_vc", nullable=false, length=45)
    public String getNacionalidadeVc() {
        return this.nacionalidadeVc;
    }
    
    public void setNacionalidadeVc(String nacionalidadeVc) {
        this.nacionalidadeVc = nacionalidadeVc;
    }

    
    @Column(name="email_vc", nullable=false, length=45)
    public String getEmailVc() {
        return this.emailVc;
    }
    
    public void setEmailVc(String emailVc) {
        this.emailVc = emailVc;
    }

    
    @Column(name="biografia_vc", nullable=false, length=45)
    public String getBiografiaVc() {
        return this.biografiaVc;
    }
    
    public void setBiografiaVc(String biografiaVc) {
        this.biografiaVc = biografiaVc;
    }

    
    @Column(name="genero_literario", nullable=false, length=45)
    public String getGeneroLiterario() {
        return this.generoLiterario;
    }
    
    public void setGeneroLiterario(String generoLiterario) {
        this.generoLiterario = generoLiterario;
    }

    
    @Column(name="destaques_vc", nullable=false, length=45)
    public String getDestaquesVc() {
        return this.destaquesVc;
    }
    
    public void setDestaquesVc(String destaquesVc) {
        this.destaquesVc = destaquesVc;
    }




}


