package BEAN;
// Generated 19/10/2023 14:15:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LeitoresVc generated by hbm2java
 */
@Entity
@Table(name="leitores_vc"
    ,catalog="db_vivian_carvalho"
)
public class LeitoresVc  implements java.io.Serializable {


     private int idleitoresVc;
     private String nomeLeitorVc;
     private String emailVc;
     private String telefoneVc;
     private String endereco;
     private Date dataNascimentoVc;
     private int statusVc;
     private String categoriaVc;
     private String observacoesVc;
     private String multaAtualVc;
     private String numeroCartaoBibliotecaVc;
     private String cpfVc;
     private String dataValidadeCartao;
     private String sexoVc;
     private String rgVc;
     private String senhaVc;
     

    public LeitoresVc() {
    }

	
    public LeitoresVc(int idleitoresVc) {
        this.idleitoresVc = idleitoresVc;
    }
    public LeitoresVc(int idleitoresVc, String nomeLeitorVc, String emailVc, String telefoneVc, String endereco, Date dataNascimentoVc, Integer statusVc, String categoriaVc, String observacoesVc, String multaAtualVc, String numeroCartaoBibliotecaVc, String cpfVc, String dataValidadeCartao, String sexoVc, String rgVc, String senhaVc, Set vendaVcs, Set vendaProdutoVcs) {
       this.idleitoresVc = idleitoresVc;
       this.nomeLeitorVc = nomeLeitorVc;
       this.emailVc = emailVc;
       this.telefoneVc = telefoneVc;
       this.endereco = endereco;
       this.dataNascimentoVc = dataNascimentoVc;
       this.statusVc = statusVc;
       this.categoriaVc = categoriaVc;
       this.observacoesVc = observacoesVc;
       this.multaAtualVc = multaAtualVc;
       this.numeroCartaoBibliotecaVc = numeroCartaoBibliotecaVc;
       this.cpfVc = cpfVc;
       this.dataValidadeCartao = dataValidadeCartao;
       this.sexoVc = sexoVc;
       this.rgVc = rgVc;
       this.senhaVc = senhaVc;
      
    }
   
     @Id 

    
    @Column(name="idleitores_vc", unique=true, nullable=false)
    public int getIdleitoresVc() {
        return this.idleitoresVc;
    }
    
    public void setIdleitoresVc(int idleitoresVc) {
        this.idleitoresVc = idleitoresVc;
    }

    
    @Column(name="nome_leitor_vc", length=45)
    public String getNomeLeitorVc() {
        return this.nomeLeitorVc;
    }
    
    public void setNomeLeitorVc(String nomeLeitorVc) {
        this.nomeLeitorVc = nomeLeitorVc;
    }

    
    @Column(name="email_vc", length=45)
    public String getEmailVc() {
        return this.emailVc;
    }
    
    public void setEmailVc(String emailVc) {
        this.emailVc = emailVc;
    }

    
    @Column(name="telefone_vc", length=45)
    public String getTelefoneVc() {
        return this.telefoneVc;
    }
    
    public void setTelefoneVc(String telefoneVc) {
        this.telefoneVc = telefoneVc;
    }

    
    @Column(name="endereco", length=45)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_vc", length=10)
    public Date getDataNascimentoVc() {
        return this.dataNascimentoVc;
    }
    
    public void setDataNascimentoVc(Date dataNascimentoVc) {
        this.dataNascimentoVc = dataNascimentoVc;
    }

    
    @Column(name="status_vc")
    public Integer getStatusVc() {
        return this.statusVc;
    }
    
    public void setStatusVc(Integer statusVc) {
        this.statusVc = statusVc;
    }

    
    @Column(name="categoria_vc", length=45)
    public String getCategoriaVc() {
        return this.categoriaVc;
    }
    
    public void setCategoriaVc(String categoriaVc) {
        this.categoriaVc = categoriaVc;
    }

    
    @Column(name="observacoes_vc", length=45)
    public String getObservacoesVc() {
        return this.observacoesVc;
    }
    
    public void setObservacoesVc(String observacoesVc) {
        this.observacoesVc = observacoesVc;
    }

    
    @Column(name="multa_atual_vc", length=45)
    public String getMultaAtualVc() {
        return this.multaAtualVc;
    }
    
    public void setMultaAtualVc(String multaAtualVc) {
        this.multaAtualVc = multaAtualVc;
    }

    
    @Column(name="numero_cartao_biblioteca_vc", length=45)
    public String getNumeroCartaoBibliotecaVc() {
        return this.numeroCartaoBibliotecaVc;
    }
    
    public void setNumeroCartaoBibliotecaVc(String numeroCartaoBibliotecaVc) {
        this.numeroCartaoBibliotecaVc = numeroCartaoBibliotecaVc;
    }

    
    @Column(name="cpf_vc", length=45)
    public String getCpfVc() {
        return this.cpfVc;
    }
    
    public void setCpfVc(String cpfVc) {
        this.cpfVc = cpfVc;
    }

    
    @Column(name="data_validade_cartao", length=45)
    public String getDataValidadeCartao() {
        return this.dataValidadeCartao;
    }
    
    public void setDataValidadeCartao(String dataValidadeCartao) {
        this.dataValidadeCartao = dataValidadeCartao;
    }

    
    @Column(name="sexo_vc", length=45)
    public String getSexoVc() {
        return this.sexoVc;
    }
    
    public void setSexoVc(String sexoVc) {
        this.sexoVc = sexoVc;
    }

    
    @Column(name="rg_vc", length=45)
    public String getRgVc() {
        return this.rgVc;
    }
    
    public void setRgVc(String rgVc) {
        this.rgVc = rgVc;
    }

    
    @Column(name="senha_vc", length=45)
    public String getSenhaVc() {
        return this.senhaVc;
    }
    
    public void setSenhaVc(String senhaVc) {
        this.senhaVc = senhaVc;
    }




}


