package BEAN;
// Generated 19/10/2023 14:15:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LivroVc generated by hbm2java
 */
@Entity
@Table(name="livro_vc"
    ,catalog="db_vivian_carvalho"
)
public class LivroVc  implements java.io.Serializable {


     private int idlivroVc;
     private String tituloVc;
     private String autorVc;
     private String generoVc;
     private String anoPublicacaoVc;
     private String quantidadeEstoqueVc;
    

    public LivroVc() {
    }

	
    public LivroVc(int idlivroVc) {
        this.idlivroVc = idlivroVc;
    }
    public LivroVc(int idlivroVc, String tituloVc, String autorVc, String generoVc, String anoPublicacaoVc, String quantidadeEstoqueVc, Set vendaProdutoVcs) {
       this.idlivroVc = idlivroVc;
       this.tituloVc = tituloVc;
       this.autorVc = autorVc;
       this.generoVc = generoVc;
       this.anoPublicacaoVc = anoPublicacaoVc;
       this.quantidadeEstoqueVc = quantidadeEstoqueVc;
       
    }
   
     @Id 

    
    @Column(name="idlivro_vc", unique=true, nullable=false)
    public int getIdlivroVc() {
        return this.idlivroVc;
    }
    
    public void setIdlivroVc(int idlivroVc) {
        this.idlivroVc = idlivroVc;
    }

    
    @Column(name="titulo_vc", length=45)
    public String getTituloVc() {
        return this.tituloVc;
    }
    
    public void setTituloVc(String tituloVc) {
        this.tituloVc = tituloVc;
    }

    
    @Column(name="autor_vc", length=45)
    public String getAutorVc() {
        return this.autorVc;
    }
    
    public void setAutorVc(String autorVc) {
        this.autorVc = autorVc;
    }

    
    @Column(name="genero_vc", length=45)
    public String getGeneroVc() {
        return this.generoVc;
    }
    
    public void setGeneroVc(String generoVc) {
        this.generoVc = generoVc;
    }

    
    @Column(name="ano_publicacao_vc", length=45)
    public String getAnoPublicacaoVc() {
        return this.anoPublicacaoVc;
    }
    
    public void setAnoPublicacaoVc(String anoPublicacaoVc) {
        this.anoPublicacaoVc = anoPublicacaoVc;
    }

    
    @Column(name="quantidade_estoque_vc", length=45)
    public String getQuantidadeEstoqueVc() {
        return this.quantidadeEstoqueVc;
    }
    
    public void setQuantidadeEstoqueVc(String quantidadeEstoqueVc) {
        this.quantidadeEstoqueVc = quantidadeEstoqueVc;
    }






}


