package BEAN;
// Generated 19/10/2023 14:15:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaVc generated by hbm2java
 */
@Entity
@Table(name="venda_vc"
    ,catalog="db_vivian_carvalho"
)
public class VendaVc  implements java.io.Serializable {


     private int idvendaVc;
     private LeitoresVc leitoresVc;
     private String dataVenda;
     private String valorTotal;
     private String formaPagamento;

    public VendaVc() {
    }

    public VendaVc(int idvendaVc, LeitoresVc leitoresVc, String dataVenda, String valorTotal, String formaPagamento) {
       this.idvendaVc = idvendaVc;
       this.leitoresVc = leitoresVc;
       this.dataVenda = dataVenda;
       this.valorTotal = valorTotal;
       this.formaPagamento = formaPagamento;
    }
   
     @Id 

    
    @Column(name="idvenda_vc", unique=true, nullable=false)
    public int getIdvendaVc() {
        return this.idvendaVc;
    }
    
    public void setIdvendaVc(int idvendaVc) {
        this.idvendaVc = idvendaVc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="leitor_id", nullable=false)
    public LeitoresVc getLeitoresVc() {
        return this.leitoresVc;
    }
    
    public void setLeitoresVc(LeitoresVc leitoresVc) {
        this.leitoresVc = leitoresVc;
    }

    
    @Column(name="data_venda", nullable=false, length=45)
    public String getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(String dataVenda) {
        this.dataVenda = dataVenda;
    }

    
    @Column(name="valor_total", nullable=false, length=45)
    public String getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(String valorTotal) {
        this.valorTotal = valorTotal;
    }

    
    @Column(name="forma_pagamento", nullable=false, length=45)
    public String getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }




}


